---
jenkins_version: "2.452.1-lts-jdk17"
jenkins_http_port: 8080
jenkins_admin_user: admin
jenkins_admin_display_name: "Admin"
jenkins_admin_password: changeme
jenkins_plugins:
  - configuration-as-code
  - git
  - workflow-aggregator
  - credentials-binding
  - docker-workflow
  - kubernetes-cli
  - job-dsl
  - ansicolor
  - timestamper
  - parameterized-trigger
  - cloudbees-folder
  - people-view
jenkins_seed_jobs: []
jenkins_registry_username: ci
jenkins_registry_password: changeme
jenkins_cli_jar: /var/lib/jenkins/jenkins-cli.jar
whanos_git_repo: "https://github.com/RaresFZ/whanos.git"
whanos_git_branch: "main"
whanos_languages:
  - c
  - java
  - javascript
  - python
  - befunge
